<div class="navbar navbar-default">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">Home</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav"><?php
                $this->partial()->setObjectKey('model');

                echo $this->partial(
                    'core-control/layout/navigation/list',
                    $this->navigation('control-navigation')->getContainer()
                );
            ?></ul>
        </div>
    </div>
</div>
